/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.netxsolutions.idx.wsq;

public class WSQWrapperJNI {
  public final static native int DecodeWSQFile(String jarg1, String jarg2);
  public final static native int EncodeWSQFile(String jarg1, String jarg2, float jarg3, int jarg4, int jarg5, String jarg6);
  public final static native int DecodeWSQToFile(String jarg1, String jarg2, int jarg3);
  public final static native int AuthenticateLicence(String jarg1, String jarg2);
}
